### PR TITLE
Fix bnd-maven-plugin configuration merging

### LINKED ISSUE #3471: EmailService not working due to unsatisfied reference to MailTemplateManager in AEM on prem
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.21
* [ ] ACS AEM Commons Version: 6.9.0+
* [ ] Reproducible on Latest? yes

### Expected Behavior

ACS Commons EmailService works in AEM on prem.

### Actual Behavior

With https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/3422 (ACS Commons 6.9.0) MailTemplateManager was introduced and added as a reference to EmailService and the implementation for the MailTemplateManager was placed in bundle-cloud and bundle-onprem. Unfortunately the bundle-onprem is missing in acs-aem-commons-all-6.9.*.zip files. Looks like the dependency entry for bundle-onprem is missing in all/pom.xml.
I did a quick try and after adding the dependency to all/pom.xml bundle-onprem was part of the resulting zip file but the build failed with:
`[ERROR] [artifact-rules] com.adobe.acs:acs-aem-commons-bundle-onprem:6.9.5-SNAPSHOT: The Adobe ACS Commons onprem bundle is not supported (adobe/consulting:acs-aem-commons-all:6.9.5-SNAPSHOT)`

In addition to the missing bundle in the zip file it looks like something with the implementation is not working. I manually installed a locally build acs-aem-commons-bundle-onprem:6.9.4 but then the following error occurred:
`java.lang.ClassNotFoundException: com.adobe.acs.commons.email.impl.MailTemplateManager not found by acs-aem-commons-bundle-onprem`

### Steps to Reproduce

For the first part of the issue AEM is not needed to reproduce this. Just open acs-aem-commons-all-6.9.*.zip and go to jcr_root\apps\acs-commons\install. There only acs-aem-commons-bundle is present and acs-aem-commons-bundle-onprem is missing. 
With AEM navigate to http://localhost:4502/system/console/components and search for com.adobe.acs.commons.email.impl.EmailServiceImpl. The status will be "unsatisfied (reference)"

For the second part navigate to http://localhost:4502/system/console/components and search for com.adobe.acs.commons.email.impl.MailTemplateManagerImpl. The status will be "satisfied" and in the error.log of AEM there will be messages like:
`java.lang.ClassNotFoundException: com.adobe.acs.commons.email.impl.MailTemplateManager not found by acs-aem-commons-bundle-onprem`

### PR DESCRIPTION
**Pull request by kwin**
Previously the configuration from the parent (per execution id) was overriding the local config (per plugin). Now the parent configuration is no longer per execution id, i.e. both local plugin configurations (i.e. on plugin level and on execution id level) take precedence.

This closes #3471

### CODE REVIEW

**Comment by kwin** [comment]
@cziegeler Can you have a look as well? Actually it doesn't seem to be a bug in bnd-maven-plugin but just a misunderstanding how the effective plugin configuration is calculated: https://issues.apache.org/jira/browse/MNGSITE-544

**Review by davidjgonzalez — APPROVED** [review]

**Comment by davidjgonzalez** [comment]
@kwin  does this address the missing onprem bundle from the all.zip as well?  IIRC from last night it wasnt being added as a dep to the all's non-cloud profile.

**Comment by davidjgonzalez** [comment]
It looks like the build is failing due to the onprem bundle failing aemanalyser checks:

```
Error:  The analyser found the following errors for author and publish : 
Error:  [artifact-rules] com.adobe.acs:acs-aem-commons-bundle-onprem:6.9.7-SNAPSHOT: The Adobe ACS Commons onprem bundle is not supported (adobe/consulting:acs-aem-commons-all:6.9.7-SNAPSHOT)
```

I ran into the same when I was trying to fix this in the other PR. Do we just skip running the analyzer for the non-cloud, and let the cloud build fail on any errors in the shared bundles? Im not seeing any way tell it to not analyze a specific artifact..?

**Comment by kwin** [comment]
@davidjgonzalez I now excluded running the aemanalyser on the classic/onprem package in https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/02ce4da2c5e4a3a52ae6a6a35e7371da3ca0be3f. It only evaluates the one with `cloud` classifier.

**Comment by davidjgonzalez** [comment]
@kwin  - This is still failing, but now it thinks jacoco is being added to the bundle, tho from what i can see that's only included w/ the test scope.


```
Error:  Failed to execute goal com.adobe.aem:aemanalyser-maven-plugin:1.6.4:project-analyse (aem-analyser) on project acs-aem-commons-all: One or more feature analyser(s) detected feature error(s), please read the plugin log for more details -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.adobe.aem:aemanalyser-maven-plugin:1.6.4:project-analyse (aem-analyser) on project acs-aem-commons-all: One or more feature analyser(s) detected feature error(s), please read the plugin log for more details
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:299)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:963)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:296)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:199)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoFailureException: One or more feature analyser(s) detected feature error(s), please read the plugin log for more details
    at com.adobe.aem.analyser.mojos.AbstractAnalyseMojo.execute (AbstractAnalyseMojo.java:152)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:299)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:963)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:296)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:199)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Error:  
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :acs-aem-commons-all
Error: Exception in thread "Thread-20" java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_4742761/core/data/ExecutionDataWriter
	at org.jacoco.agent.rt.internal_4742761.output.FileOutput.writeExecutionData(FileOutput.java:63)
	at org.jacoco.agent.rt.internal_4742761.Agent.shutdown(Agent.java:145)
	at org.jacoco.agent.rt.internal_4742761.Agent$1.run(Agent.java:58)
Caused by: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_4742761.core.data.ExecutionDataWriter
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	... 3 more
Error: Process completed with exit code 1.
```

**Comment by kwin** [comment]
The relevant error is

```
Error:  [api-regions-exportsimports] com.adobe.acs:acs-aem-commons-bundle-cloud:6.10.0-SNAPSHOT: Bundle acs-aem-commons-bundle-cloud:6.10.0-SNAPSHOT is importing package(s) org.jacoco.agent.rt.internal_4742761 in start level 20 but no bundle is exporting these for that start level. (adobe/consulting:acs-aem-commons-all:6.10.0-SNAPSHOT)
```

Not sure how the Jacoco agent may affect the Manifest generation and why that error was not emitted before...

**Comment by kwin** [comment]
Turns out the reason is offline instrumentation for jacoco (compare with https://www.eclemma.org/jacoco/trunk/doc/offline.html and https://www.eclemma.org/jacoco/trunk/doc/faq.html). It is unclear to me why Jacoco Offline instrumentation is used at all (introduced with https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/7cb5929227c4960f65fd8907dccd676c475830b5, due to #1321). As powermock is no longer used, we should completely get rid of it. Also it is not clear to me how CodeCov is related to Jacoco. IMHO only the former is used with ACS AEM Commons (https://docs.codecov.com/docs/quick-start).

**Comment by jdavenport-vervio** [comment]
Hello @kwin @davidjgonzalez when is this change planned to be released? We are dependent on this issue being fixed to complete our service pack upgrade, thank you
