### ISSUE TITLE
Fix test failures when building/testing with Java 11

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-commons#1916]
### Expected Behavior

The master branch should build fine with Java 11

### Actual Behavior

There are test failures being emitted. For further details refer to the failed build from https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1912.

**Comment by kwin** [comment]
@ahmed-musallam Is that something you could look into since you already provided the fix for the compilation error in #1893?

**Comment by ahmed-musallam** [comment]
@kwin I was randomly browsing when I stumbled on this.. for some reason I did not get a notification.

Any way, it looks like #1976 fixes this issue?

**Comment by kwin** [comment]
@ahmed-musallam I just rebased my PR in #1912  but still there are some build/test execution failures in Java11 (https://travis-ci.org/Adobe-Consulting-Services/acs-aem-commons/jobs/580427352#L23735):

> [ERROR] Errors: 
[ERROR]   PowerMockErrorPageCacheImplTest.initializationError » Objenesis java.lang.refl...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   BrandPortalSyncProcessTest.initializationError » Objenesis java.lang.reflect.I...
[INFO] 
[ERROR] Tests run: 1453, Failures: 0, Errors: 10, Skipped: 0

Maybe they are fixed once #1924, #1925  and #1931 are merged...

**Comment by joerghoh** [comment]
I don't think that the issues have been fixed:

```
oerg@linux-7u5z:~/repos/acs-aem-commons> mvn -version
Apache Maven 3.5.4 (SUSE 3.5.4-1.5)
Maven home: /usr/share/maven
Java version: 11.0.5, vendor: Oracle Corporation, runtime: /usr/lib64/jvm/java-11-openjdk-11
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "5.3.7-1-default", arch: "amd64", family: "unix"
joerg@linux-7u5z:~/repos/acs-aem-commons>
``` 

I get this output on current master

```
[ERROR] Errors: 
[ERROR]   PowerMockErrorPageCacheImplTest.initializationError » Objenesis java.lang.refl...
[ERROR]   RemoteAssetDecoratorTest.testGetResourceHandlesExceptionWaitingForSyncInProgress » Runtime
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   BrandPortalSyncProcessTest.initializationError » Objenesis java.lang.reflect.I...
[INFO] 
[ERROR] Tests run: 1478, Failures: 0, Errors: 11, Skipped: 0
```

**Comment by joerghoh** [comment]
Working on it, #2104. Is likely to take some time.
