### ISSUE TITLE
Multi field dialog is not working on AEM 6.5 and ACS common 4.0.0

### ISSUE THREAD

**Issue by tusharnetake** [Adobe-Consulting-Services/acs-aem-commons#1887]
## Required Information

* [6.5 ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _____AEM 6.5__
* [ 4.0.0] ACS AEM Commons Version: _4.0.0____
* [ Yes] Reproducible on Latest? yes/no

### Expected Behavior
We are trying to upgrade to AEM 6.5 from AEM 6.3. We are facing issue in ACS common feature multi field . We are using ACS commons multifield in our components and We were using ACS commons 3.17.0 on AEM 6.3 and now we have to use ACS commons 4.0.0 on AEM 6.5 as 3.17.0 is not supported on AEM 6.5. 

Whenever we are opening component dialog for edit , all fields are showing empty and its not populating values in the dialog and also its not storing anything in the repository once we submit dialog

As mentioned in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/apps/acs-commons/touchui-widgets/composite-multifield/.content.xml#L9 
We have added wrapper client library in the the our project>client library but still its not working.

While Page loading i can see below error message in the browser console 

Uncaught ReferenceError: Class is not defined
    at composite-multifield.js:34
    at composite-multifield.js:395

Also whenever i am opening dialog i can see below error in the console 

all.js:166 Uncaught TypeError: $(...).fontIconPicker is not a function
at HTMLDocument.<anonymous> (all.js:166)
at HTMLDocument.dispatch (jquery.js:5226)
at HTMLDocument.elemData.handle (jquery.js:4878)
at Object.trigger (jquery.js:5130)
at HTMLElement.<anonymous> (jquery.js:5860)
at Function.each (jquery.js:370)
at jQuery.fn.init.each (jquery.js:137)
at jQuery.fn.init.trigger (jquery.js:5859)
at core.js:653
at jquery.js:3411

--

### Actual Behavior

Multi field dialog should retain values and also store values to the repository. 

### Steps to Reproduce

_Starting from a vanilla instance of AEM at the above version, describe in explicit steps how to reproduce. Link to
any supporting assets, e.g. content packages, below_

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by anjalibiddanda** [comment]
Hi Tushar, I'm seeing the same issue with Multifield (granite/ui/components/foundation/form/multifield) when upgrading to AEM6.5- https://forums.adobe.com/thread/2627022.
Did you happen to resolve this?

**Comment by anjalibiddanda** [comment]
@davidjgonzalez , I'm seeing the same issue with Multifield (granite/ui/components/foundation/form/multifield) when upgrading to AEM6.5- https://forums.adobe.com/thread/2627022. Any suggestions?
Did you happen to resolve this @tusharnetake ?
