### PR TITLE
use offline instrumentation for jacoco. fixes #1321

### LINKED ISSUE #1321: Jacoco Powermock issue
Hi Team,

We are working on AEM 6.3 Project.  We are using Jacoco plugin to generate the code coverage report.
Power mocks are ignored in the final report.
jacoco report has issues with Powermock. So, we need to do offline Instrumentation.

https://github.com/powermock/powermock/wiki/Code-coverage-with-JaCoCo
http://www.eclemma.org/jacoco/trunk/doc/offline.html

We need to do same in acs-aem-commons as well if we use power mocks.

I would like increase overall code coverage as well.

 AEM Version  6.3
ACS AEM Commons Version: Latest : 3.14.13-SNAPSHOT

Thanks & Regards,
Prasad.

### PR DESCRIPTION
**Pull request by justinedelson**

### CODE REVIEW

**Comment by justinedelson** [comment]
So the build says it passed, but the coverage data wasn't actually posted. And running the build locally, I get some animal-sniffer errors.

**Comment by justinedelson** [comment]
Fixed the animal sniffer problem, but now getting

Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_c13123e/core/data/ExecutionDataWriter
	at org.jacoco.agent.rt.internal_c13123e.output.FileOutput.writeExecutionData(FileOutput.java:55)
	at org.jacoco.agent.rt.internal_c13123e.Agent.shutdown(Agent.java:137)
	at org.jacoco.agent.rt.internal_c13123e.Agent$1.run(Agent.java:54)
Caused by: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_c13123e.core.data.ExecutionDataWriter
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 3 more
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_c13123e/core/data/ExecutionDataWriter
	at org.jacoco.agent.rt.internal_c13123e.output.FileOutput.writeExecutionData(FileOutput.java:55)
	at org.jacoco.agent.rt.internal_c13123e.Agent.shutdown(Agent.java:137)
	at org.jacoco.agent.rt.internal_c13123e.Agent$1.run(Agent.java:54)
Caused by: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_c13123e.core.data.ExecutionDataWriter
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 3 more

which at least I can reproduce locally

**Comment by justinedelson** [comment]
@prasadu-boggavarapu have you run into this exception?

**Comment by justinedelson** [comment]
Error is visible here: https://api.travis-ci.org/v3/job/364882605/log.txt

**Comment by justinedelson** [comment]
OK. With all that fiddling, I think I finally landed on the right solution.

**Comment by prasadu-boggavarapu** [comment]
Great. 

Sorry for the late response. It is late night here in Germany. So I slept.
I got many issues initially. I fixed all those. Most of the issues resolved after adding the scanner.


                <plugin>
                    <groupId>org.sonarsource.scanner.maven</groupId>
                    <artifactId>sonar-maven-plugin</artifactId>
                    <version>3.4.0.905</version>
                </plugin>


and I added profile for sonar.

<profile>
            <id>sonar</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                
                <sonar.host.url>
                    http://localhost:9000
                </sonar.host.url>
            </properties>
        </profile>



Could you please provide commit rights to me. I would like to write few Junit test cases.
Going forward I will work on new features as well.

Thanks,
Prasad.

**Comment by justinedelson** [comment]
Any new test/features should be added through pull requests.

**Comment by prasadu-boggavarapu** [comment]
Ya. Would like to create a new feature branch for me. I will add my Junit test cases in that. 
We need commit rights for that I guess.

**Comment by justinedelson** [comment]
You don't need commit rights. Please read https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/CONTRIBUTING.md#how-to-contribute-code
